### ISSUE TITLE
Update Website & Registry

### ISSUE THREAD

**Issue by ksnydes** [styfle/checklist#15]
- [x] Venue name & address
- [x] Information about airport
- [x] Seasonal Indiana weather tips for those visiting from out of state - dress in layers, it has potential to get quite chilly at night
- [x] Info about formality of dress - nice casual 
- [x] Our engagement story/add timeline somehow

**Comment by styfle** [comment]
I have a great idea. We could host our website on GitHub for free and make it super geeky!
See this one for an idea: http://justgrimes.github.io/wedding/

**Comment by ksnydes** [comment]
Hmmm.... Would that be more work than the one we have already? Can we do RSVPs on it? (that's going to be the most helpful things - having digital RSVPs)

**Comment by styfle** [comment]
I can work something out. Let's see how The Knot authenticates users when they RSVP, then I can copy that :smile:

**Comment by styfle** [comment]
I updated our URL slug to *thatsalatoflove*

**Comment by ksnydes** [comment]
@styfle do you think it would be possible to have a weather monitor on our website? Like a mini weather app for the week of our wedding?
