### ISSUE TITLE
Block Out Hotel Rooms for Guests

### ISSUE THREAD

**Issue by ksnydes** [styfle/checklist#17]
- [x] Visit Hotels in the area
- [x] Talk with/Meet with Hotel Owners/Managers

**Comment by styfle** [comment]
Almost complete?

**Comment by ksnydes** [comment]
We are getting there. It hasn't been set because my mom hasn't signed the contract. We don't have the rooms blocked yet.

**Comment by styfle** [comment]
How about now? :smile:

**Comment by styfle** [comment]
"The block was for 35 rooms - 25 with a king, 10 with two queens"
Still waiting on the URL for #113

@ksnydes Is it safe to tell family they can book now by calling the hotel?

**Comment by ksnydes** [comment]
Yes, they can call the hotel to book now
