### ISSUE TITLE
Make Rehearsal Dinner Guest List

### ISSUE THREAD

**Issue by ksnydes** [styfle/checklist#35]
So we can include their invitation to it in wedding invitations? (or should we have invitations be verbal/via email for rehearsal diner?)

**Comment by styfle** [comment]
I saw you added a column for Hotel. Is this different than the rehearsal guest list?

**Comment by ksnydes** [comment]
Yes, this is different

**Comment by ksnydes** [comment]
There is a separate rehearsal dinner column that we can use. The hotel column could be deleted since that was just what I used to estimate how many rooms we would need to block out
