### ISSUE TITLE
Send bridal party invites

### ISSUE THREAD

**Issue by styfle** [styfle/checklist#4]
## For K
- [x] Decide who will be in bridal party
- [x] Brainstorm ideas of how to ask them
- [x] Send out "will you be my bridesmaid" package/gift/card

## For S
- [x] Select Best Man (or best men)
- [x] Ask groomsmen (via phone?)

**Comment by styfle** [comment]
Did you ever find your gifts that you hid so well? :laughing:

**Comment by ksnydes** [comment]
I found them this morning. I'll be sending them out this weekend or Monday

**Comment by styfle** [comment]
I think this is done? :grin:

**Comment by ksnydes** [comment]
Unfortunately, not yet :/ I'm not doing so great at this one.
