### ISSUE TITLE
Schedule Counseling with DS?

### ISSUE THREAD

**Issue by ksnydes** [styfle/checklist#55]

**Comment by ksnydes** [comment]
We need to talk about whether we want to do skype with DS or in person with someone local

**Comment by styfle** [comment]
DS Pros:
* I know him really well, 10+ years
* Typically the officiant also does counceling so they can kinda talk about the couple
* You don't know him that well so it will be good to get to know him better before Oct
* He does this for a living: marriage/family therapist

Local Pros:
* Get to know local people better
* No skype lag
* Same time zone so hours might be easier

**Comment by styfle** [comment]
@ksnydes 
He said Friday through Sunday works best.
Any preference here?

**Comment by ksnydes** [comment]
@styfle , I guess Saturday or Sunday afternoon would be my preference

**Comment by styfle** [comment]
Sunday 12th and noon
